FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY main.py main.py

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main:app"]
